name: Release
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}

    - id: latest
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "binhollc/SupernovaFirmware"
        token: ${{ secrets.PAT_TOKEN }}
        latest: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: "binho_supernova_firmware_images_v${{ steps.latest.outputs.tag_name }}"
        path: ${{github.workspace}}/*

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{github.workspace}}/*.hex
          ${{github.workspace}}/*.gfi

